CREATE TABLE [adi].[Amerigroup_Member] (
    [AmerigroupMemberKey]                  INT           NOT NULL,
    [OriginalFileName]                     VARCHAR (100) NOT NULL,
    [SrcFileName]                          VARCHAR (100) NOT NULL,
    [LoadDate]                             DATE          NOT NULL,
    [CreatedDate]                          DATE          NOT NULL,
    [DataDate]                             DATE          NOT NULL,
    [FileDate]                             DATE          NOT NULL,
    [CreatedBy]                            VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]                      DATETIME      NOT NULL,
    [LastUpdatedBy]                        VARCHAR (50)  NOT NULL,
    [MasterConsumerID]                     BIGINT        NULL,
    [MemberCode]                           VARCHAR (3)   NULL,
    [HealthCardIdentifier]                 VARCHAR (50)  NULL,
    [DateofBirth]                          DATE          NULL,
    [FirstName]                            VARCHAR (50)  NULL,
    [LastName]                             VARCHAR (50)  NULL,
    [PCPAssignmentMethodCode]              VARCHAR (3)   NULL,
    [BusinessUnit]                         VARCHAR (150) NULL,
    [MemberAddress]                        VARCHAR (200) NULL,
    [MemberCity]                           VARCHAR (50)  NULL,
    [MemberState]                          VARCHAR (50)  NULL,
    [MemberZip]                            VARCHAR (10)  NULL,
    [PrimaryLanguage]                      VARCHAR (500) NULL,
    [GroupNumber]                          VARCHAR (20)  NULL,
    [GroupName]                            VARCHAR (100) NULL,
    [SubgroupNum]                          VARCHAR (32)  NULL,
    [SubgroupName]                         VARCHAR (100) NULL,
    [BNFTPKGID]                            VARCHAR (25)  NULL,
    [Responsible_Tax_ID_Could_Contain_SSN] VARCHAR (15)  NULL,
    [EffectiveDate]                        DATE          NULL,
    [TerminationDate]                      DATE          NULL,
    [MemberPhone]                          VARCHAR (10)  NULL,
    [BNFTPKGName]                          VARCHAR (200) NULL,
    [MemberKey]                            VARCHAR (32)  NULL,
    [AlphaPrefixID]                        VARCHAR (3)   NULL,
    [FundingChartfieldCode]                VARCHAR (3)   NULL,
    [Responsible_NPI]                      VARCHAR (15)  NULL,
    [EnterpriseMembercode]                 VARCHAR (3)   NULL,
    [MemberSequenceNumber]                 VARCHAR (15)  NULL,
    [ChronicCareFlag]                      VARCHAR (10)  NULL,
    [PLN_ST_CD]                            VARCHAR (3)   NULL,
    [HOST_IND_CD]                          VARCHAR (1)   NULL,
    [JAA_IND_CD]                           VARCHAR (3)   NULL,
    [INSERT_UPDATE_IND]                    VARCHAR (1)   NULL,
    [ATRBN_TRMNTN_RSN_CD]                  VARCHAR (10)  NULL,
    [REDACT_FLAG]                          VARCHAR (1)   NULL,
    [Contract_Type]                        VARCHAR (5)   NULL,
    [PROD_SOR_CD]                          VARCHAR (10)  NULL,
    [PG_ID]                                VARCHAR (32)  NULL,
    [PG_NAME]                              VARCHAR (100) NULL,
    [PGM_ID]                               VARCHAR (32)  NULL,
    [Panel_ID]                             VARCHAR (32)  NULL,
    [PLAN_DESC]                            VARCHAR (80)  NULL,
    [Medicaid_could_contain_ssn]           VARCHAR (20)  NULL,
    [HICN_could_contain_ssn]               VARCHAR (20)  NULL,
    [Ethnicity]                            VARCHAR (7)   NULL,
    [WrittenLanguage]                      VARCHAR (500) NULL,
    [MemberCounty]                         VARCHAR (25)  NULL,
    [LOB]                                  VARCHAR (100) NULL,
    [Gender]                               VARCHAR (10)  NULL,
    [RowStatus]                            TINYINT       NOT NULL
);

