CREATE TABLE [adi].[Amerigroup_MedClaimHdr] (
    [MedClaimHdrKey]                          INT             NOT NULL,
    [OriginalFileName]                        VARCHAR (100)   NOT NULL,
    [SrcFileName]                             VARCHAR (100)   NOT NULL,
    [LoadDate]                                DATE            NOT NULL,
    [CreatedDate]                             DATE            NOT NULL,
    [DataDate]                                DATE            NOT NULL,
    [FileDate]                                DATE            NOT NULL,
    [CreatedBy]                               VARCHAR (50)    NOT NULL,
    [LastUpdatedDate]                         DATETIME        NOT NULL,
    [LastUpdatedBy]                           VARCHAR (50)    NOT NULL,
    [MasterConsumerID]                        BIGINT          NULL,
    [ClaimNbr]                                VARCHAR (24)    NULL,
    [ClaimAdjustmentNum]                      DECIMAL (4)     NULL,
    [ClaimDispositionCode]                    VARCHAR (5)     NULL,
    [BillingProviderLicenseNum]               VARCHAR (15)    NULL,
    [BillingProviderTaxID]                    VARCHAR (15)    NULL,
    [MedicareID]                              VARCHAR (15)    NULL,
    [PaidDate]                                DATE            NULL,
    [DRG]                                     VARCHAR (15)    NULL,
    [BilledServiceUnitCount]                  DECIMAL (18, 3) NULL,
    [PaidServiceUnitCount]                    DECIMAL (18, 3) NULL,
    [NumDays]                                 DECIMAL (4)     NULL,
    [BillType]                                VARCHAR (4)     NULL,
    [InpatientTransplantFlag]                 VARCHAR (5)     NULL,
    [AdmitType]                               VARCHAR (3)     NULL,
    [AdmitSource]                             VARCHAR (3)     NULL,
    [AdmitHour]                               DECIMAL (2)     NULL,
    [DischargeStatus]                         VARCHAR (5)     NULL,
    [BillingProviderNPI]                      VARCHAR (25)    NULL,
    [AttendingProviderNPI]                    VARCHAR (25)    NULL,
    [AdmittingProviderNPI]                    VARCHAR (25)    NULL,
    [ServiceRenderingProviderNPI]             VARCHAR (25)    NULL,
    [OtherProviderNPI]                        VARCHAR (25)    NULL,
    [ReferringProviderLicenseNum]             VARCHAR (25)    NULL,
    [ProfessionalIndicator]                   VARCHAR (5)     NULL,
    [InstitutionalIndicator]                  VARCHAR (5)     NULL,
    [FNL_MS_DRG]                              VARCHAR (5)     NULL,
    [ICD_CM_procedure1]                       VARCHAR (15)    NULL,
    [ICD_CM_procedure2]                       VARCHAR (15)    NULL,
    [ICD_CM_procedure3]                       VARCHAR (15)    NULL,
    [ICD_CM_procedure4]                       VARCHAR (15)    NULL,
    [ICD_CM_procedure5]                       VARCHAR (15)    NULL,
    [FromDate]                                DATE            NULL,
    [ToDate]                                  DATE            NULL,
    [AdmitDate]                               DATE            NULL,
    [Billing_provider_id]                     VARCHAR (15)    NULL,
    [Billing_providercode]                    VARCHAR (10)    NULL,
    [ServiceproviderId]                       VARCHAR (15)    NULL,
    [Serviceprovidercode]                     VARCHAR (25)    NULL,
    [Member_Key]                              VARCHAR (32)    NULL,
    [InternationalClassificationDiseasesCode] VARCHAR (10)    NULL,
    [REDACT_FLAG]                             VARCHAR (15)    NULL,
    [DischargeDate]                           DATE            NULL,
    [DRG_Type_Code]                           VARCHAR (15)    NULL,
    [PG_ID]                                   VARCHAR (32)    NULL,
    [PG_NAME]                                 VARCHAR (100)   NULL,
    [CLM_ADJSTMNT_KEY]                        VARCHAR (32)    NULL,
    [Actual_Paid_Date]                        DATE            NULL,
    [Claim_Processed_Date]                    DATE            NULL
);

