CREATE TABLE [adi].[Amerigroup_CARE-OPPS] (
    [Amerigroup_CARE-OPPSKey] INT           NOT NULL,
    [OriginalFileName]        VARCHAR (100) NOT NULL,
    [SrcFileName]             VARCHAR (100) NOT NULL,
    [LoadDate]                DATE          NOT NULL,
    [CreatedDate]             DATE          NOT NULL,
    [DataDate]                DATE          NOT NULL,
    [FileDate]                DATE          NOT NULL,
    [CreatedBy]               VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]         DATETIME      NOT NULL,
    [LastUpdatedBy]           VARCHAR (50)  NOT NULL,
    [MasterConsumerID]        BIGINT        NULL,
    [HealthCardIdentifier]    VARCHAR (50)  NULL,
    [FirstName]               VARCHAR (50)  NULL,
    [LastName]                VARCHAR (50)  NULL,
    [DateBirth]               DATE          NULL,
    [Gender]                  VARCHAR (3)   NULL,
    [EnterpriseMemberCode]    VARCHAR (3)   NULL,
    [MemberSequenceNumber]    VARCHAR (15)  NULL,
    [MSR_CMPLNC_CD]           VARCHAR (32)  NULL,
    [RULE_ID]                 VARCHAR (8)   NULL,
    [ANLYSS_AS_OF_DT]         DATE          NULL,
    [LAST_SRVC_DT]            DATE          NULL,
    [RULE_NM]                 VARCHAR (255) NULL,
    [PG_ID]                   VARCHAR (32)  NULL,
    [PG_NAME]                 VARCHAR (100) NULL,
    [PGM_ID]                  VARCHAR (32)  NULL,
    [Panel_ID]                VARCHAR (32)  NULL,
    [MemberKey]               VARCHAR (32)  NULL,
    [MSR_NMRTR_NBR]           VARCHAR (3)   NULL,
    [MSR_DNMNTR_NBR]          VARCHAR (3)   NULL,
    [NEXT_CLNCL_DUE_DT]       DATE          NULL,
    [MSRMNT_PRD_STRT_DT]      DATE          NULL,
    [MSRMNT_PRD_END_DT]       DATE          NULL,
    [LatestValue]             VARCHAR (100) NULL,
    [AttributionAsDate]       DATE          NULL
);

