CREATE TABLE [adi].[Amerigroup_MedClaimDetl] (
    [Amerigroup_MedClaimDetlKey]  INT             NOT NULL,
    [OriginalFileName]            VARCHAR (100)   NOT NULL,
    [SrcFileName]                 VARCHAR (100)   NOT NULL,
    [LoadDate]                    DATE            NOT NULL,
    [CreatedDate]                 DATE            NOT NULL,
    [DataDate]                    DATE            NOT NULL,
    [FileDate]                    DATE            NOT NULL,
    [CreatedBy]                   VARCHAR (50)    NOT NULL,
    [LastUpdatedDate]             DATETIME        NOT NULL,
    [LastUpdatedBy]               VARCHAR (50)    NOT NULL,
    [MasterConsumerID]            BIGINT          NULL,
    [ClaimNbr]                    VARCHAR (24)    NULL,
    [ClaimAdjustmentNum]          DECIMAL (4)     NULL,
    [ClaimDispositionCode]        VARCHAR (5)     NULL,
    [LineNumber]                  VARCHAR (6)     NULL,
    [FromDate]                    DATE            NULL,
    [EndDate]                     DATE            NULL,
    [StatusCode]                  VARCHAR (5)     NULL,
    [ReasonCode]                  VARCHAR (100)   NULL,
    [Year]                        VARCHAR (4)     NULL,
    [Quarter]                     VARCHAR (6)     NULL,
    [Month]                       VARCHAR (6)     NULL,
    [HealthServiceCode]           VARCHAR (8)     NULL,
    [RevenueCode]                 VARCHAR (8)     NULL,
    [HealthServiceCodeModifier]   VARCHAR (5)     NULL,
    [NumberServiceUnits]          DECIMAL (18, 3) NULL,
    [LineBilled]                  DECIMAL (18, 2) NULL,
    [LineCovered]                 DECIMAL (18, 2) NULL,
    [PlaceService]                VARCHAR (5)     NULL,
    [ContractFlag1]               VARCHAR (3)     NULL,
    [DIAG_1_CD]                   VARCHAR (10)    NULL,
    [DIAG_2_CD]                   VARCHAR (10)    NULL,
    [DIAG_3_CD]                   VARCHAR (10)    NULL,
    [DIAG_4_CD]                   VARCHAR (10)    NULL,
    [DIAG_5_CD]                   VARCHAR (10)    NULL,
    [InpatientFlag]               VARCHAR (3)     NULL,
    [PotentiallyAvoidableERflag]  VARCHAR (3)     NULL,
    [Imagingflag]                 VARCHAR (3)     NULL,
    [AdmitthruERFlag]             VARCHAR (3)     NULL,
    [MemberKey]                   VARCHAR (32)    NULL,
    [ICDVersionCode]              VARCHAR (10)    NULL,
    [Claim_SOR_CD]                VARCHAR (10)    NULL,
    [Billedserviceunitcount]      DECIMAL (18, 3) NULL,
    [Paidserviceunitcount]        DECIMAL (18, 3) NULL,
    [PatientResponsibilityAmount] DECIMAL (18, 2) NULL,
    [LineAllowed]                 DECIMAL (18, 2) NULL,
    [LinePaid]                    DECIMAL (18, 2) NULL,
    [REDACT_FLAG]                 VARCHAR (1)     NULL,
    [HLTH_SRVC_TYPE_CD]           VARCHAR (5)     NULL,
    [PG_ID]                       VARCHAR (32)    NULL,
    [PG_NAME]                     VARCHAR (100)   NULL,
    [CLM_ADJSTMNT_KEY]            CHAR (32)       NULL,
    [IN_OUTNetworkclaims]         VARCHAR (3)     NULL,
    [Denial_Reason_Code]          VARCHAR (32)    NULL,
    [Denial_Reason_Description]   VARCHAR (1000)  NULL
);

