CREATE TABLE [adi].[Amerigroup_MedProvider] (
    [Amerigroup_MedProviderKey]      INT           NOT NULL,
    [OriginalFileName]               VARCHAR (100) NOT NULL,
    [SrcFileName]                    VARCHAR (100) NOT NULL,
    [LoadDate]                       DATE          NOT NULL,
    [CreatedDate]                    DATE          NOT NULL,
    [DataDate]                       DATE          NOT NULL,
    [FileDate]                       DATE          NOT NULL,
    [CreatedBy]                      VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]                DATETIME      NOT NULL,
    [LastUpdatedBy]                  VARCHAR (50)  NOT NULL,
    [PROV_LCNS_ID]                   VARCHAR (25)  NULL,
    [MedicareID_Could_Contain_SSN]   VARCHAR (20)  NULL,
    [Provider_Tax_ID]                VARCHAR (16)  NULL,
    [LicensureCode]                  VARCHAR (50)  NULL,
    [ProviderLastName]               VARCHAR (70)  NULL,
    [ProviderFirstName]              VARCHAR (40)  NULL,
    [ProviderSpecialty]              VARCHAR (50)  NULL,
    [AddressLine1]                   VARCHAR (100) NULL,
    [AddressLine2]                   VARCHAR (100) NULL,
    [ProviderCity]                   VARCHAR (50)  NULL,
    [ProviderState]                  VARCHAR (3)   NULL,
    [ProviderZipCode]                VARCHAR (6)   NULL,
    [ProviderPhone]                  VARCHAR (50)  NULL,
    [DEANum]                         VARCHAR (25)  NULL,
    [NPI]                            VARCHAR (25)  NULL,
    [TaxonomyCode]                   VARCHAR (10)  NULL,
    [ContractFlag1]                  VARCHAR (3)   NULL,
    [ProviderBusinessName_GroupName] VARCHAR (70)  NULL,
    [REDACTFLAG]                     VARCHAR (1)   NULL,
    [PG_ID]                          VARCHAR (32)  NULL,
    [PG_NAME]                        VARCHAR (150) NULL
);

